### ISSUE TITLE
Not parsing 'flat' yaml correctly for application properties

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#180]
doing an update such as
`upgrade --release-name ticktockskipper --package-name ticktock --package-version 1.0.0 --property-string log.spec.applicationProperties.log.level=INFO
`

results in the yaml 

```
spec:
  resource: maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.1.0.RELEASE
  resourceMetadata: maven://org.springframework.cloud.stream.app:log-sink-rabbit:jar:metadata:1.1.0.RELEASE
  applicationProperties:
    log.level: DEBUG
    log: {level&#x3D;INFO}
  deploymentProperties:
    memory: 1024m
```

which jackson can't handle correctly.

**Comment by markpollack** [comment]
after pretty printing, we are getting it nested

```  
log:
      spec:
          applicationProperties:
              log:
                  level: INFO
```
with propertynames that have a 'dot' in them, it will next.  maybe we can use a dash instead?
