### ISSUE TITLE
[Skipper+CF] Auto-bind to required services isn't working

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#202]
As a user, I'm supplying the `streamServices` (see env-var below) as part of the Skipper manifest file; however, the apps don't appear to be auto-binding to required services. I don't see them being mapped [here](https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/service/DeployerInitializationService.java#L118-L158). And because of that reason, though the apps spawn correctly, the service binding isn't applied.

```
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[DEV]_CONNECTION_STREAM_SERVICES: rabbit,redis
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[DEV]_CONNECTION_TASK_SERVICES: mysql
```

(_where `DEV` is the platform name (aka: deployer-name) that I'm using in my testing_)

**Comment by markpollack** [comment]
The YAML in the test was wrong.  It should be

```
          cloudfoundry:
            accounts:
              dev:
                connection:
                  url: https://api.run.pivotal.io
                  org: myOrg
                  space: mySpace
                  domain: cfapps.io
                  username: skipper@example.com
                  password: drowssap
                  skipSslValidation: false
                deployment:
                  memory: 512m
                  disk: 2048m
                  instances: 4
                  services: rabbit,mysql
```

There is only a `services` property in `CloudFoundryDeploymentProperties`.  The SCDF server for CF does some tricks to create two instances of this call for task and apps.  We only deploy apps anyway via skipper.

```
	@Bean
	@ConfigurationProperties(prefix = CloudFoundryConnectionProperties.CLOUDFOUNDRY_PROPERTIES + ".stream")
	public CloudFoundryDeploymentProperties appDeploymentProperties() {
		return new CloudFoundryDeploymentProperties();
	}

	@Bean
	@ConfigurationProperties(prefix = CloudFoundryConnectionProperties.CLOUDFOUNDRY_PROPERTIES + ".task")
	public CloudFoundryDeploymentProperties taskDeploymentProperties() {
		return new CloudFoundryDeploymentProperties();
	}
```
and in the autoconfig

```	public static class EarlyConnectionConfiguration {

		@Bean
		@ConditionalOnMissingBean(name = "appDeploymentProperties")
		public CloudFoundryDeploymentProperties appDeploymentProperties() {
			return defaultSharedDeploymentProperties();
		}


		@Bean
		@ConditionalOnMissingBean(name = "taskDeploymentProperties")
		public CloudFoundryDeploymentProperties taskDeploymentProperties() {
			return defaultSharedDeploymentProperties();
		}

		@Bean
		@ConfigurationProperties(prefix = CLOUDFOUNDRY_PROPERTIES)
		public CloudFoundryDeploymentProperties defaultSharedDeploymentProperties() {
			return new CloudFoundryDeploymentProperties();
		}```

And those beans are picked up when `CloudFoundryAppDeployer` and `CloudFoundry2630AndLaterTaskLauncher` are created.

I'm closing the issue for now after updating the tests.  Please retry and we can open again if it doesn't work.
