### ISSUE TITLE
Property values look to be modified when parsing yaml out of property string.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#265]
I am not sure where the bug is located, but when I did the following
```
skipper:>install --release-name helloworld-pcf3 --package-name helloworld --package-version 1.0.0 --platform-name cf-dev --properties spec.deploymentProperties.spring.cloud.deployer.cloudfoundry.route=mlp3-helloworld.cfapps.io
```
what I got for the manifest was
```
skipper:>manifest get --release-name helloworld-pcf3 --release-version 1

---
# Source: helloworld.yml
apiVersion: skipper/v1
kind: SpringBootApp
metadata:
  name: helloworld
  type: demo
spec:
  resource: maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld:1.0.0.RELEASE
  applicationProperties:
  deploymentProperties:
    spring.cloud.deployer.cloudfoundry.route: mlp3.helloworld.cfapps.io
```

Somehow the `dash` between `mlp3-helloworld` was converted to a `dot`
