### ISSUE TITLE
Add support for YAML based nesting of `applicationProperties` and `deploymentProperties`

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#315]
It would be convenient, and in a way expected, to specify deployment properties in this way

```
spec:
  applicationProperties:
    endpoints:
      sensitive: false
    helloworld:
      greeting: yo
  deploymentProperties:
    spring:
      cloud:
      deployer:
        cloudfoundry:
          route: helloworldpcf.cfapps.io
          apiTimeout: 500
```
instead of 

```
spec:
  applicationProperties:
    endpoints.sensitive: false
    helloworld.greeting: yo
  deploymentProperties:
    spring.cloud.deployer.cloudfoundry.route: helloworldpcf.cfapps.io
    spring.cloud.deployer.cloudfoundry.apiTimeout: 500
```

The savings in this example is really around the setting of `deploymentProperties`, but as a general feature this applies to `applicationProperties`
