### ISSUE TITLE
1.0.1 BS image is not available in Docker Hub

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#550]
As a user, while trying the getting-started guide in SCDF; everything comes up except the Skipper-server. The Skipper deployment fails because the 1.0.1 BS tag is not available in [Docker hub](https://hub.docker.com/r/springcloud/spring-cloud-skipper-server/tags/).

Note: We also need to automate 1.0.1.RELEASE tagging as part of the first maintenance release.

**Comment by markpollack** [comment]
Section 1.3 now has a yml file fragment showing

```
 spec:
      containers:
      - name: scdf-server
        image: springcloud/spring-cloud-dataflow-server-kubernetes:latest   
        imagePullPolicy: Always
```

and https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-kubernetes/tags/ shows `latest` now build snapshot.



There isn't a way to automate the tagging via bamboo due to the separate build stage.  There are a few other manual steps as part of the release, if we want to automate that further we should create a separate issue.  ATM, the manual steps are not that bothersome.
