### ISSUE TITLE
Randomized App name inconsistencies on Cloud Foundry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#689]
As an SCDF user, while deploying a stream from SCDF, I notice the deployed app names have randomized prefixes. 

I attempted to override it via `SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_CONNECTION_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: false`, but that doesn't seem to change the behavior.

This particularly complicates the situation when I'm also trying to bind a "config-server" instance to the Apps, where the property file naming should match the deployed App name.

**Comment by jvalkeal** [comment]
@sabbyanandan Not really sure why docs say to use that format, but when I moved that setting(in skipper server) from `connection` to `deployment` per:

```
spring:
  cloud:
    skipper:
      server:
        platform:
          cloudfoundry:
            accounts:
              cf-dev:
                connection:
                  url: https://api.run.pivotal.io
                  org: scdf-ci
                  space: space-janne
                  domain: cfapps.io
                  skipSslValidation: false
                deployment:
                  deleteRoutes: false
                  enableRandomAppNamePrefix: false
```


App names changed per:

```
jvalkealahti@neo:~/work/skipper$ cf apps
Getting apps in org scdf-ci / space space-janne as jvalkealahti@pivotal.io...
OK

name                         requested state   instances   memory   disk   urls
rTQEgvE-myticktock-log-v1    started           0/1         1G       1G     rTQEgvE-myticktock-log-v1.cfapps.io
rTQEgvE-myticktock-time-v1   started           0/1         1G       1G     rTQEgvE-myticktock-time-v1.cfapps.io

jvalkealahti@neo:~/work/skipper$ cf apps
Getting apps in org scdf-ci / space space-janne as jvalkealahti@pivotal.io...
OK

name                 requested state   instances   memory   disk   urls
myticktock-log-v1    started           1/1         1G       1G     myticktock-log-v1.cfapps.io
myticktock-time-v1   started           0/1         1G       1G     myticktock-time-v1.cfapps.io
```
