### ISSUE TITLE
Overhaul CF Manifest file handling

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#695]
1. I think we need to be strict how additional files are processed. I.e in this case manifest deployer is simply trying to find first file ending with `manifest.yml`. Then values are updated from template.

2. This have few issues like install blows up if manifest file is not it place. Also as manifest file is same format as one from CF, only first application entry is used. All these feels rather awkward.

Maybe it'd be better to have a source of thruth in template like:

```
apiVersion: skipper.spring.io/v1
kind: CloudFoundryApplication
spec:
  manifest:
    name: jannelogcf
    memory: 1024
    disk_quota: 1024
    timeout: 180
    instances: 1
    path: log-sink-rabbit-1.1.0.RELEASE.jar
    services: rabbit

```

and then if we really want to insert something into `spec.manifest`, maybe we can extend mustache templates to read/export additional files from a package.

child of #627
