### ISSUE TITLE
Change package-repositories from list to map

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#789]
Currently we use repos as list.
```
spring:
  cloud:
    skipper:
      server:
        packageRepositories:
          -
            name: experimental
            url: http://skipper-repository.cfapps.io/repository/experimental
            description: Experimental Skipper Repository
            repoOrder: 0
          -
            name: local
            url: http://${spring.cloud.client.hostname}:7577
            local: true
            description: Default local database backed repository
            repoOrder: 1
```
This effectively is hardcoding these into a config as complex list of objects is makes it impossible to override anything and modification needs to re-write everything.

Having these as a map where key is a repo name would suit needs better as then overriding something is accurate and clear.
