### ISSUE TITLE
Some api endpoints stop responding after a while

### ISSUE THREAD

**Issue by rstpv** [spring-cloud/spring-cloud-skipper#952]
After updating to the latest dataflow and skipper version, the left panel of dataflow stopped working, the about call returned 404 error, this was described in:
https://github.com/spring-cloud/spring-cloud-dataflow/issues/3924

After debugging the issue a little bit I saw that the pod with skipper running did indeed returned 404 after some time running.

This is the response when invoking Skipper api with curl after it gets in a wrong state:
`curl -i http://skipper.somenamespace.svc.cluster.local/api`

```json
{
  "_links" : {
    "about" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/about"
    },
    "release" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/release"
    },
    "package" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/package"
    },
    "profile" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/profile"
    }
  }
}
```

If I restart the skipper pod the response becomes:

```
{
  "_links" : {
    "deployers" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/deployers{?page,size,sort}",
      "templated" : true
    },
    "repositories" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/repositories{?page,size,sort}",
      "templated" : true
    },
    "packageMetadata" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/packageMetadata{?page,size,sort,projection}",
      "templated" : true
    },
    "releases" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/releases{?page,size,sort}",
      "templated" : true
    },
    "about" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/about"
    },
    "release" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/release"
    },
    "package" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/package"
    },
    "profile" : {
      "href" : "http://skipper.somenamespace.svc.cluster.local/api/profile"
    }
  }
}
```

**Comment by sabbyanandan** [comment]
@rstpv: I just left a comment on the SCDF issue. Either here or in SCDF, if you can describe your provisioning method, environment, and any other customization details that you have in your set up, we can have a look.

**Comment by rstpv** [comment]
For provisioning we are using the helm chart for dataflow.
Environment Amazon EKS.
Dataflow version: 2.5.0.RELEASE
Skipper version: 2.4.0.RELEASE

As for customization I was thinking if maybe having a custom platform might cause the issue.
  
```
  spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                     **properties
                  otherplatformname:
                      **otherproperties
                      namespace: customnamespace
```
The issue happens randomly after some time, so not sure what steps to follow.

I will rollback to dataflow 2.4.2.RELEASE and skipper 2.3.0.RELEASE to see if it helps to solve the issue(The additional platform name was a recent change on our setup, that was done at the same time as the update).

**Comment by jvalkeal** [comment]
This indeed is weird as that root page is served from spring-hateoas and I've never seen that links could just get removed. We'll try to reproduce.

**Comment by sabbyanandan** [comment]
@rstpv: Thanks for the info! Please retain the extra platform account when you revert to 2.4; let's see if it happens in that combination.

**Comment by jvalkeal** [comment]
@rstpv Could you tell which jvm you're using and any other what comes to your mind about about settings, etc.

**Comment by rstpv** [comment]
Regarding other settings:    
```
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 300m
          memory: 1Gi
```
The database we are using its postgressql.
We also have some podAnnotations:
`podAnnotations: 'prometheus.io/path:/actuator/prometheus,prometheus.io/port:8080,prometheus.io/scrape:true,prometheus.io/scheme:http,sidecar.istio.io/inject:false`

We are running it with the embedded kafka in one env and an external kafka in other.

Pretty much everything else is as it is in the helm chart.

We have rolled back to the previous version, I'll update the issue if the problem happens with that version too.
